# Generated by Django 5.2.17 on 2026-09-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_seed_internal_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='LeadStream', max_length=120)),
                ('logo_url_dark', models.URLField(blank=True, default='', max_length=500)),
                ('logo_url_light', models.URLField(blank=True, default='', max_length=500)),
                ('favicon_url', models.URLField(blank=True, default='', max_length=500)),
                ('accent_color', models.CharField(default='#10B981', max_length=32)),
                ('support_email', models.EmailField(blank=True, default='suporte@leadstream.com.br', max_length=254)),
                ('terms_url', models.URLField(blank=True, default='', max_length=500)),
                ('privacy_url', models.URLField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração White-Label',
                'verbose_name_plural': 'Configurações White-Label',
                'db_table': 'leadstream_platform_branding',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_batch_size',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_concurrency',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
