# Generated by Django 5.2.17 on 2026-09-11 21:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_seed_internal_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("prefix", models.CharField(db_index=True, max_length=16)),
                ("hashed_key", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("OPERATOR", "Operador"),
                            ("READ_ONLY", "Somente Leitura"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chave de API",
                "verbose_name_plural": "Chaves de API",
                "db_table": "security_api_keys",
                "indexes": [
                    models.Index(
                        fields=["prefix", "is_active"], name="security_ap_prefix_2e2aae_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.CharField(blank=True, default="", max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("resource_accessed", models.CharField(blank=True, default="", max_length=255)),
                ("status_code", models.IntegerField(default=200)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria de Segurança",
                "verbose_name_plural": "Logs de Auditoria de Segurança",
                "db_table": "security_audit_logs",
                "indexes": [
                    models.Index(
                        fields=["tenant", "timestamp"], name="security_au_tenant__78b36d_idx"
                    ),
                    models.Index(
                        fields=["action", "timestamp"], name="security_au_action_0492cf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("OPERATOR", "Operador"),
                            ("READ_ONLY", "Somente Leitura"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo de Workspace",
                "verbose_name_plural": "Vínculos de Workspace",
                "db_table": "security_workspace_memberships",
                "indexes": [
                    models.Index(
                        fields=["user", "tenant", "is_active"],
                        name="security_wo_user_id_fb7b7e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tenant"), name="unique_user_tenant_membership"
                    )
                ],
            },
        ),
    ]
