# Generated by Django 5.2.17 on 2026-09-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_providercall_delivered_blocks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providercall",
            name="execution_token",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name="providercall",
            name="leased_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providercall",
            name="next_poll_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providercall",
            name="provider_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
