# Generated by Django 5.2.17 on 2026-09-10 20:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0004_remove_batchchunk_batch_chunk_seq_uniq_and_more"),
        ("tenancy", "0002_seed_internal_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PROCESSING", "Processando"),
                            ("COMPLETED", "Concluído"),
                            ("FAILED", "Falhou"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("file_backend", models.CharField(default="LOCAL", max_length=32)),
                ("file_key", models.CharField(blank=True, max_length=512)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "content_type",
                    models.CharField(default="text/csv; charset=utf-8", max_length=128),
                ),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("selected_columns", models.JSONField(blank=True, default=list)),
                ("selected_statuses", models.JSONField(blank=True, default=list)),
                ("lead_level", models.CharField(default="DECISION_MAKER", max_length=32)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("total_companies", models.PositiveIntegerField(default=0)),
                ("total_decision_makers", models.PositiveIntegerField(default=0)),
                ("total_direct_contacts", models.PositiveIntegerField(default=0)),
                ("manifest_data", models.JSONField(blank=True, default=dict)),
                ("export_hash", models.CharField(blank=True, max_length=64)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="batches.batch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_batch_export",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "batch", "status"], name="batch_export_status_idx"
                    ),
                    models.Index(fields=["tenant", "export_hash"], name="batch_export_hash_idx"),
                ],
            },
        ),
    ]
