# Generated by Django 5.2.17 on 2026-09-10 21:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("batches", "0005_batchexport"),
        ("tenancy", "0002_seed_internal_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("HUBSPOT", "HubSpot"),
                            ("PIPEDRIVE", "Pipedrive"),
                            ("RD_STATION", "RD Station CRM"),
                            ("SALESFORCE", "Salesforce"),
                            ("PLOOMES", "Ploomes"),
                            ("ZOHO", "Zoho CRM"),
                            ("AGENDOR", "Agendor"),
                            ("KOMMO", "Kommo (amoCRM)"),
                            ("WEBHOOK_CUSTOM", "Webhook Universal (HMAC)"),
                            ("WEBHOOK_N8N", "Webhook n8n"),
                            ("WEBHOOK_ZAPIER", "Webhook Zapier"),
                            ("WEBHOOK_MAKE", "Webhook Make"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("UNTESTED", "Não testado"),
                            ("HEALTHY", "Operacional"),
                            ("DEGRADED", "Degradado"),
                            ("FAILED", "Falha de autenticação/conexão"),
                        ],
                        default="UNTESTED",
                        max_length=16,
                    ),
                ),
                ("last_error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_crm_connection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMSyncEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("total_enqueued", models.PositiveIntegerField(default=0)),
                ("total_delivered", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="PROCESSING", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_sync_events",
                        to="batches.batch",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_events",
                        to="integrations.crmconnection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_crm_sync_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMFieldMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Empresa"),
                            ("CONTACT", "Contato / Decisor"),
                            ("DEAL", "Oportunidade / Negócio"),
                        ],
                        default="COMPANY",
                        max_length=16,
                    ),
                ),
                ("source_field", models.CharField(max_length=100)),
                ("target_field", models.CharField(max_length=100)),
                (
                    "transformation",
                    models.CharField(
                        choices=[
                            ("RAW", "Sem transformação (direto)"),
                            ("LOWER", "Minúsculo"),
                            ("UPPER", "Maiúsculo"),
                            ("DIGITS_ONLY", "Apenas dígitos (números)"),
                            ("FIRST_NAME", "Primeiro nome"),
                            ("LAST_NAME", "Sobrenome"),
                        ],
                        default="RAW",
                        max_length=16,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="integrations.crmconnection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_crm_field_mapping",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "entity_type", "source_field"),
                        name="unique_crm_field_mapping_per_connection_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CRMOutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Empresa"),
                            ("CONTACT", "Contato / Decisor"),
                            ("DEAL", "Oportunidade / Negócio"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=255)),
                ("canonical_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PROCESSING", "Em processamento"),
                            ("DELIVERED", "Entregue"),
                            ("FAILED", "Falha temporária (aguardando retry)"),
                            ("DEAD_LETTER", "Falha definitiva (Dead Letter)"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=5)),
                (
                    "next_retry_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("remote_id", models.CharField(blank=True, max_length=255)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("execution_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_outbox_messages",
                        to="batches.batch",
                    ),
                ),
                (
                    "batch_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_outbox_messages",
                        to="batches.batchitem",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_messages",
                        to="integrations.crmconnection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_crm_outbox_message",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "idempotency_key"),
                        name="unique_crm_outbox_per_connection_key",
                    )
                ],
            },
        ),
    ]
