# Generated by Django 5.2.17 on 2026-09-14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        ("tenancy", "0003_platformbranding_tenant_max_batch_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("crm_target", models.CharField(blank=True, max_length=80)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_activation_list",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "archived_at", "updated_at"],
                        name="activation_list_state_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivationListMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activation_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="analytics.activationlist",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_list_memberships",
                        to="entities.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_activation_list_member",
                "ordering": ["added_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "entity"],
                        name="activation_member_entity_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activation_list", "entity"),
                        name="activation_list_entity_uniq",
                    )
                ],
            },
        ),
    ]
