# Generated by Django 5.2.17 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("entities", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_size",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_nature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="mei",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_cnae",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_cnae_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="company",
            name="registry_observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="registry_source",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="company",
            name="secondary_cnaes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="company",
            name="share_capital",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="simple_national",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="city",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="establishment",
            name="complement",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="establishment",
            name="district",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="establishment",
            name="municipality_ibge_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="establishment",
            name="number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="establishment",
            name="postal_code",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="establishment",
            name="state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="establishment",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="establishment",
            name="street_type",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
