# Generated by Django 5.2.17 on 2026-09-14

import uuid

import django.db.models.deletion
from django.db import migrations, models

import leadstream.common.encrypted_fields


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0002_discoverysearch_discoveryresult_and_more"),
        ("tenancy", "0002_seed_internal_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("COMPANY", "Pessoa jurídica"), ("PERSON", "Pessoa física")],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("query_digest", models.CharField(max_length=64)),
                ("query_label", models.CharField(max_length=32)),
                (
                    "input_payload",
                    leadstream.common.encrypted_fields.EncryptedJSONField(default=dict),
                ),
                ("capabilities", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Na fila"),
                            ("RUNNING", "Em execução"),
                            ("SUCCEEDED", "Concluído"),
                            ("NO_DATA", "Sem resultado"),
                            ("FAILED", "Falhou"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                (
                    "result_payload",
                    leadstream.common.encrypted_fields.EncryptedJSONField(blank=True, default=dict),
                ),
                ("matched_entity_id", models.CharField(blank=True, max_length=64)),
                ("cost_credits", models.PositiveIntegerField(default=0)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("lease_owner", models.CharField(blank=True, max_length=255)),
                ("leased_until", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("purge_after", models.DateTimeField()),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "leadstream_enrichment_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "created_at"],
                        name="enrich_job_status_idx",
                    ),
                    models.Index(
                        fields=["status", "leased_until"],
                        name="enrich_job_lease_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "idempotency_key"),
                        name="enrichment_job_tenant_idem_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gte", 1), ("max_attempts__lte", 10)),
                        name="enrichment_job_attempts_range",
                    ),
                ],
            },
        )
    ]
